### ISSUE TITLE
The ground plane really shouldn't cross the isolation slot

### ISSUE THREAD

**Issue by jaseg** [hborisov/switcher_pcb#1] opened 2016-09-20 21:43 UTC
... because that kind of defeats the purpose of the isolation slot.

Best regards, jaseg

**Comment by hborisov** [comment] 2016-09-21 18:42
Yes, I agree. I will correct this one, thank you!

**Comment by hborisov** [comment] 2016-11-18 21:06
The issue is fixed now.

**Closed as completed by hborisov** 2016-11-18 21:06 UTC
